.Dd 2016-02-25
.Dt COLLATZ 1
.Os nbase
.Sh NAME
.Nm collatz
.Nd print collatz sequences
.Sh SYNOPSIS
.Nm
.Op numbers
.Sh DESCRIPTION
.Nm
prints the collatz sequence of either the cli arguments
.Ar numbers
or the input. The output sequence is separated by spaces.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Program exited normally after processing all arguments.
.It > 1
An error occurred.
.El
