.TH COLLATZ 1
.SH NAME
collatz \- print the collatz sequence of the input

.SH SYNOPSIS
collatz [NUMBERS]

.SH DESCRIPTION
collatz prints the collatz sequence of either the command line arguments
or the input, separated by spaces.

.SH STATUS
0 on success and 1 when a libzahl error occurs.

.SH AUTHOR
pranomostro (pranomestro@gmail.com).
