.Dd 2016-02-25
.Dt FAC 1
.Os nbase
.Sh NAME
.Nm fac
.Nd print factorials
.Sh SYNOPSIS
.Nm
.Op numbers
.Sh DESCRIPTION
.Nm
prints all it's input/cli arguments, together with a colon and the
factorial of that number.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Program exited normally after processing all arguments.
.It > 1
An error occurred.
.El
