.Dd 2016-02-25
.Dt FACTOR 1
.Os nbase
.Sh NAME
.Nm factor
.Nd prime factor numbers
.Sh SYNOPSIS
.Nm
.Op Fl c Ar N
.Op Fl p Ar N
.Op Fl q
.Op Ar number ...
.Sh DESCRIPTION
.Nm
prints the prime factors of
.Ar number .
If no
.Ar number
has been specified, the numbers to factor are
line by line from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar N
Select the certainty for prime factors. The probably
that a composite number will be listed as a prime
factor will be less than 4^(-\fIN\fP).
.It Fl p Ar N
Use at most
.Ar N
threads to factor each
.Ar number .
This is seldom useful.
Note, the input numbers are not factored concurrently,
only their factors.
.It Fl q
Mark factors with \(aq?\(aq if it is not certain that
they are prime.
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
All numbers were successfully factorized.
.It > 1
An error occurred.
.El
.Sh NOTES
The factors are not output in ascending order,
but in order of discovery.
.Pp
The prime test is two-stage. The first stage
is unaffected by the
.Fl c
flag. In this stage it is possible that the
number is designated as a prime with complete
certainty. In second stage, which is affected
by the
.Fl c
flag, the number cannot be designated as a
prime with complete certainty.
.Sh SEE ALSO
.Xr bc 1
