.TH FIB 1
.SH NAME
fib \- print the nth fibonacci number

.SH SYNOPSIS
fib [NUMBERS]

.SH DESCRIPTION
fac prints its input, followd by a colon and the fibonacci number of
either the command line arguments or the input.

.SH STATUS
0 on success and 1 when a libzahl error occurs.

.SH AUTHOR
pranomostro (pranomestro@gmail.com).
