.Dd 2016-02-25
.Dt LEYLAND 1
.Os nbase
.Sh NAME
.Nm leyland
.Nd print the leyland numbers
.Sh SYNOPSIS
.Nm
.Op Fl l Ar N
.Sh DESCRIPTION
.Nm
prints the N first (or all) leyland numbers (every number representable
with a^b+b^a where a==b!=1) in ascending order.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl l Ar N
Print only the
.Ar N
first leyland numbers.
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
The program terminated successfully.
.It > 1
An error occurred.
.El
